'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ciLayoutDesignVB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property __UI_for_V831_v101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("__UI for V831_v101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property __UI_for_V831_w_No_Pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("__UI for V831 w No Pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property __UI_for_v900_w_demo_face() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("__UI for v900 w demo face", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdjustWHColor_V101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdjustWHColor_V101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdjustWHColor_V102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdjustWHColor_V102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdjustWHColor_V103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdjustWHColor_V103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property C39FIRA() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("C39FIRA", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CI_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CI_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CI_Logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CI_Logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CISolutionsLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CISolutionsLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Context_AlignMenuSubmenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Context_AlignMenuSubmenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ContextMenu_AlignSubmenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenu_AlignSubmenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ContextMenu_grouped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenu_grouped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ContextMenu_non_grouped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenu_non_grouped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ContextMenu_non_grouped1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenu_non_grouped1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DecreaseY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DecreaseY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property

        ''<summary>
        ''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset0 Code39FiveRedA;}}
        ''{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
        ''\pard\sa200\sl276\slmult1\f0\fs22\lang9\par
        ''\par
        ''\f1\fs48 75757575757575757575cccccccc999989898989898HFHFHFHFHFH\f0\par
        ''\par
        ''\fs22\par
        ''}
        '' .
        ''</summary>
        Friend ReadOnly Property Font_Code39FiveRedA() As String
            Get
                Return ResourceManager.GetString("Font_Code39FiveRedA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IncreaseY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncreaseY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JaneMulvey_1015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JaneMulvey_1015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mainback_v82() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainback_v82", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SizeAdjustmentBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SizeAdjustmentBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Step3_TakePic_v82() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Step3_TakePic_v82", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Step3_TakePic_v90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Step3_TakePic_v90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Textbox_v90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Textbox_v90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property The_UI_for_v900() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("The UI for v900", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property V381() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("V381", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
